using System.IO.Compression;
using System.Text;
using Lume.Core;

internal static class DesktopFeatureTests
{
    public static void Register(Action<string, Action> test, string root)
    {
        void Check(bool ok) { if (!ok) throw new Exception("断言失败"); }
        void Reject(Action action) { try { action(); } catch (Exception ex) when (ex is InvalidDataException or InvalidOperationException or IOException or System.Xml.XmlException) { return; } throw new Exception("应拒绝无效输入"); }
        var area = new CardPlacement(-1920, 0, 1920, 1040);
        test("多屏负坐标和越界尺寸约束", () => Check(LayoutEngine.Constrain(new(-2200, 900, 4000, 800), area) == new CardPlacement(-1920, 240, 1920, 800)));
        test("八方向缩放保持对边与最小尺寸", () => { foreach (var edge in new[] { "N", "S", "W", "E", "NW", "NE", "SW", "SE" }) { var p = LayoutEngine.Resize(new(100, 100, 330, 340), edge, 1000, 1000); Check(p.Width >= 240 && p.Height >= 160); if (edge.Contains('W')) Check(p.X + p.Width == 430); if (edge.Contains('N')) Check(p.Y + p.Height == 440); } });
        test("分区边缘吸附产生实际对齐线", () => { var r = LayoutEngine.Snap(new(105, 403, 330, 340), [new(100, 50, 330, 350)], new(0, 0, 1920, 1080)); Check(r.Placement.X == 100 && r.Placement.Y == 400 && r.Guides.Count == 2); });
        test("远离目标不吸附", () => { var p = new CardPlacement(213, 317, 330, 340); var r = LayoutEngine.Snap(p, [], new(0, 0, 1920, 1080)); Check(r.Placement == p && r.Guides.Count == 0); });
        test("缩放吸附保持固定边", () => { var r = LayoutEngine.Snap(new(100, 200, 327, 340), [new(430, 800, 330, 200)], new(0, 0, 1920, 1080), edges: "E"); Check(r.Placement.X == 100 && r.Placement.Width == 330 && r.Placement.Y == 200); });
        test("自动排列避让锁定分区且不重叠", () => { var fixedCard = new CardPlacement(16, 16); var cards = LayoutEngine.Arrange(5, new(0, 0, 1920, 1040), [fixedCard]); var all = cards.Append(fixedCard).ToList(); Check(cards.Count == 5); for (int i = 0; i < all.Count; i++) for (int j = i + 1; j < all.Count; j++) Check(all[i].X + all[i].Width <= all[j].X || all[j].X + all[j].Width <= all[i].X || all[i].Y + all[i].Height <= all[j].Y || all[j].Y + all[j].Height <= all[i].Y); });
        test("排列空间不足原子拒绝", () => Reject(() => LayoutEngine.Arrange(30, new(0, 0, 640, 480), [])));
        test("布局备份往返保留锁定折叠排序", () => { var p = new DesktopPreferences { Positions = new() { ["work"] = new(-1400, 160, 480, 420) }, Cards = new() { ["work"] = new(true, true, "modified", true, 48) }, SnapEnabled = false }; var path = Path.Combine(root, "layout.json"); LayoutBackup.Write(path, p); var restored = LayoutBackup.Apply(LayoutBackup.Read(path), new() { ContextMenuEnabled = false }, ["work"]); Check(restored.Positions["work"] == p.Positions["work"] && restored.Cards["work"] == p.Cards["work"] && !restored.SnapEnabled && !restored.ContextMenuEnabled); });
        test("布局恢复忽略已删除分区", () => { var p = new DesktopPreferences { Positions = new() { ["deleted"] = new(10, 10) } }; Check(LayoutBackup.Apply(LayoutBackup.Capture(p), new(), ["work"]).Positions.Count == 0); });
        test("布局拒绝异常坐标和排序", () => { Reject(() => LayoutBackup.Validate(new(1, new() { ["x"] = new(int.MinValue, 0) }, [], 130, true))); Reject(() => LayoutBackup.Validate(new(1, [], new() { ["x"] = new(Sort: "invalid") }, 130, true))); });
        var fixture = Path.Combine(root, "feature-files"); Directory.CreateDirectory(fixture);
        Organizer Create(string name) => new(new StateStore(Path.Combine(root, name, "state.json")), AppState.Create([fixture]));
        test("映射目录监控去重且删除映射保留原文件", () => { var mapped = Path.Combine(root, "mapped"); Directory.CreateDirectory(mapped); var path = Path.Combine(mapped, "原文件.txt"); File.WriteAllText(path, "保留"); var o = Create("mapping"); o.AddMappedCollection(mapped); var c = o.State.Configuration.Collections.Last(); o.ApplyScan(DesktopScanner.Scan(o.WatchRoots)); Check(o.CollectionFiles(c.Id).Count == 1 && o.CollectionFiles("work").Count == 0); Reject(() => o.Assign(path, c.Id)); o.DeleteCollection(c.Id); Check(File.ReadAllText(path) == "保留"); });
        test("最近文件按修改时间且最多四十项", () => { var o = Create("recent"); o.AddRecentCollection(); o.AddRecentCollection(); var files = Enumerable.Range(0, 50).Select(i => new DesktopFile(Path.Combine(fixture, i + ".txt"), i + ".txt", ".txt", i, DateTime.UtcNow, new DateTime(2026, 1, 1).AddDays(i), false, "未知")).ToList(); o.ApplyScan(new(files, [])); var c = o.State.Configuration.Collections.Single(c => c.Recent); Check(o.CollectionFiles(c.Id).Count == 40 && o.CollectionFiles(c.Id)[0].Name == "49.txt"); });
        test("外部文件拖入只引用选中文件并支持单步撤销", () => { var external = Path.Combine(root, "external"); Directory.CreateDirectory(external); var selected = Path.Combine(external, "选择.txt"); File.WriteAllText(selected, "原内容"); File.WriteAllText(Path.Combine(external, "不导入.txt"), "其他"); var o = Create("drop"); o.AssignMany([selected], "work"); Check(o.Files.Count == 1 && o.CollectionFiles("work").Count == 1); var scan = DesktopScanner.Scan(o.WatchRoots, o.State.Configuration.LinkedFiles); Check(scan.Files.Count == 1); o.Undo(); Check(o.Files.Count == 0 && o.State.Configuration.LinkedFiles.Count == 0 && File.ReadAllText(selected) == "原内容"); });
        test("拖入批次有失效文件时不部分导入", () => { var o = Create("drop-invalid"); Reject(() => o.AssignMany([Path.Combine(root, "missing.txt")], "work")); Check(o.State.Configuration.LinkedFiles.Count == 0 && o.State.History.Count == 0); });
        test("排序和分区选项重启持久化", () => { var o = Create("options"); o.SetOptions("work", new(true, true, "size", true, 48)); o.SavePlacement("work", new(-1800, 40, 480, 360)); var loaded = new StateStore(Path.Combine(root, "options", "state.json")).Load([]); Check(loaded.Desktop.Cards["work"].Locked && loaded.Desktop.Positions["work"].X == -1800); });
        test("UTF8截断不把中文误识别为GBK", () => { var path = Path.Combine(root, "boundary.txt"); File.WriteAllText(path, new string('a', 131071) + "中文内容", new UTF8Encoding(false)); var text = FilePreview.ReadText(path); Check(text.StartsWith(new string('a', 131071)) && !text.Contains('�') && text.Contains("128 KB")); });
        test("UTF16和GBK中文预览", () => { var path = Path.Combine(root, "encoding.txt"); File.WriteAllText(path, "中文预览", Encoding.Unicode); Check(FilePreview.ReadText(path) == "中文预览"); Encoding.RegisterProvider(CodePagesEncodingProvider.Instance); File.WriteAllText(path, "中文预览", Encoding.GetEncoding(936)); Check(FilePreview.ReadText(path) == "中文预览"); });
        void Zip(string path, params (string Name, string Content)[] parts) { using var zip = ZipFile.Open(path, ZipArchiveMode.Create); foreach (var p in parts) { using var writer = new StreamWriter(zip.CreateEntry(p.Name).Open()); writer.Write(p.Content); } }
        test("Word文档读取段落且不改动源文件", () => { var path = Path.Combine(root, "preview.docx"); Zip(path, ("word/document.xml", "<document><p><t>项目计划</t></p><p><t>第二段</t></p></document>")); var bytes = File.ReadAllBytes(path); var text = FilePreview.ReadText(path); Check(text.Contains("项目计划") && text.Contains("第二段") && bytes.SequenceEqual(File.ReadAllBytes(path))); });
        test("Excel共享字符串和数值单元格", () => { var path = Path.Combine(root, "preview.xlsx"); Zip(path, ("xl/worksheets/sheet1.xml", "<worksheet><row><c t='s'><v>0</v></c><c><v>123</v></c></row></worksheet>"), ("xl/sharedStrings.xml", "<sst><si><t>销售额</t></si></sst>")); Check(FilePreview.ReadText(path).Contains("销售额\t123")); });
        test("PowerPoint幻灯片文字预览", () => { var path = Path.Combine(root, "preview.pptx"); Zip(path, ("ppt/slides/slide1.xml", "<sld><p><r><t>演示标题</t></r></p></sld>")); Check(FilePreview.ReadText(path).Contains("演示标题")); });
        test("压缩包仅列目录不释放文件", () => { var path = Path.Combine(root, "preview.zip"); Zip(path, ("../不应释放.txt", "内容")); Check(FilePreview.ReadText(path).Contains("不应释放.txt") && !File.Exists(Path.Combine(root, "不应释放.txt"))); });
        test("文档拒绝外部实体", () => { var path = Path.Combine(root, "bad.docx"); Zip(path, ("word/document.xml", "<!DOCTYPE doc [<!ENTITY x SYSTEM 'file:///C:/Windows/win.ini'>]><doc><p><t>&x;</t></p></doc>")); Reject(() => FilePreview.ReadText(path)); });
        test("预览拒绝过大文件但媒体允许流式读取", () => { var path = Path.Combine(root, "large.txt"); using (var f = File.Create(path)) f.SetLength(FilePreview.MaximumBytes + 1); Reject(() => FilePreview.Validate(path)); var media = Path.Combine(root, "large.mp4"); File.Move(path, media); FilePreview.Validate(media); });
    }
}
